-- MySQL Script generated by MySQL Workbench
-- 10/06/16 22:23:18
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dash
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dash` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema dash
-- -----------------------------------------------------
USE `dash` ;

-- -----------------------------------------------------
-- Table `dash`.`TB_Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dash`.`TB_Endereco` (
  `end_id` INT NOT NULL AUTO_INCREMENT,
  `end_rua` VARCHAR(200) NOT NULL,
  `end_bairro` VARCHAR(50) NOT NULL,
  `end_cidade` VARCHAR(45) NOT NULL,
  `end_estado` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`end_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dash`.`TB_Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dash`.`TB_Pessoa` (
  `pes_id` INT NOT NULL AUTO_INCREMENT,
  `pes_nome` VARCHAR(45) NOT NULL,
  `pes_telelone` VARCHAR(45) NOT NULL,
  `pes_dataNasc` DATE NOT NULL,
  `end_id` INT NOT NULL,
  `pes_numeroDoc1` VARCHAR(45) NOT NULL,
  `pes_numeroDoc2` VARCHAR(45) NOT NULL,
  `pes_sexo` CHAR NOT NULL,
  `pes_login` VARCHAR(20) NOT NULL,
  `pes_senha` VARCHAR(455) NOT NULL,
  `pes_ehAluno` INT NOT NULL DEFAULT 0,
  `pes_ehProfessor` INT NOT NULL DEFAULT 0,
  `pes_email` VARCHAR(45) NOT NULL,
  `pes_email2` VARCHAR(45) NULL,
  `pes_ehSysAdmin` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`pes_id`),
  INDEX `fk_TB_Pessoa_TB_Endereco1_idx` (`end_id` ASC),
  CONSTRAINT `fk_TB_Pessoa_TB_Endereco1`
    FOREIGN KEY (`end_id`)
    REFERENCES `dash`.`TB_Endereco` (`end_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dash`.`TB_Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dash`.`TB_Curso` (
  `cur_id` INT NOT NULL AUTO_INCREMENT,
  `cur_dataIni` DATE NOT NULL,
  `cur_dataFim` DATE NOT NULL,
  `cur_desc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cur_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dash`.`TB_Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dash`.`TB_Disciplina` (
  `dis_id` INT NOT NULL AUTO_INCREMENT,
  `dis_des` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dis_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dash`.`TB_Grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dash`.`TB_Grade` (
  `gra_id` INT NOT NULL AUTO_INCREMENT,
  `gra_disid` INT NOT NULL,
  `gra_curid` INT NOT NULL,
  PRIMARY KEY (`gra_id`),
  INDEX `fk_Grade_Disciplina_idx` (`gra_disid` ASC),
  INDEX `fk_Grade_Curso1_idx` (`gra_curid` ASC),
  CONSTRAINT `fk_Grade_Disciplina`
    FOREIGN KEY (`gra_disid`)
    REFERENCES `dash`.`TB_Disciplina` (`dis_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grade_Curso1`
    FOREIGN KEY (`gra_curid`)
    REFERENCES `dash`.`TB_Curso` (`cur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dash`.`TB_Imagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dash`.`TB_Imagem` (
  `img_id` INT NOT NULL AUTO_INCREMENT,
  `img_imagem` BLOB NOT NULL,
  `img_nome` VARCHAR(45) NULL,
  `img_pesid` INT NOT NULL,
  PRIMARY KEY (`img_id`),
  INDEX `fk_TB_Imagem_Pessoa1_idx` (`img_pesid` ASC),
  CONSTRAINT `fk_TB_Imagem_Pessoa1`
    FOREIGN KEY (`img_pesid`)
    REFERENCES `dash`.`TB_Pessoa` (`pes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dash`.`TB_Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dash`.`TB_Turma` (
  `tur_id` INT NOT NULL AUTO_INCREMENT,
  `tur_desc` VARCHAR(25) NOT NULL,
  `tur_curid` INT NOT NULL,
  PRIMARY KEY (`tur_id`),
  INDEX `fk_TB_Turma_TB_Curso1_idx` (`tur_curid` ASC),
  CONSTRAINT `fk_TB_Turma_TB_Curso1`
    FOREIGN KEY (`tur_curid`)
    REFERENCES `dash`.`TB_Curso` (`cur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dash`.`TB_ProfDisc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dash`.`TB_ProfDisc` (
  `prodis_id` INT NOT NULL AUTO_INCREMENT,
  `prodis_pesid` INT NOT NULL,
  `prodis_disid` INT NOT NULL,
  INDEX `fk_TB_Pessoa_has_TB_Disciplina_TB_Disciplina1_idx` (`prodis_disid` ASC),
  INDEX `fk_TB_Pessoa_has_TB_Disciplina_TB_Pessoa1_idx` (`prodis_pesid` ASC),
  PRIMARY KEY (`prodis_id`),
  CONSTRAINT `fk_TB_Pessoa_has_TB_Disciplina_TB_Pessoa1`
    FOREIGN KEY (`prodis_pesid`)
    REFERENCES `dash`.`TB_Pessoa` (`pes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_Pessoa_has_TB_Disciplina_TB_Disciplina1`
    FOREIGN KEY (`prodis_disid`)
    REFERENCES `dash`.`TB_Disciplina` (`dis_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dash`.`TB_Mensagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dash`.`TB_Mensagem` (
  `msg_id` INT NOT NULL AUTO_INCREMENT,
  `msg_conteudo` VARCHAR(4000) NOT NULL,
  `msg_assunto` VARCHAR(45) NOT NULL,
  `msg_horaEnvio` DATETIME NOT NULL,
  `status` INT(1) NOT NULL,
  `msg_msgrid` INT NOT NULL,
  `msg_idrem` INT NOT NULL,
  `ativo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`msg_id`),
  INDEX `fk_TB_Mensagem_TB_Pessoa1_idx` (`msg_idrem` ASC),
  CONSTRAINT `fk_TB_Mensagem_TB_Pessoa1`
    FOREIGN KEY (`msg_idrem`)
    REFERENCES `dash`.`TB_Pessoa` (`pes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dash`.`TB_MensagemDest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dash`.`TB_MensagemDest` (
  `msgd_id` INT NOT NULL AUTO_INCREMENT,
  `msgd_ativo` INT(1) NOT NULL,
  `msgd_pesid` INT NOT NULL,
  `msgd_msgid` INT NOT NULL,
  PRIMARY KEY (`msgd_id`),
  INDEX `fk_TB_MensagemDest_TB_Pessoa1_idx` (`msgd_pesid` ASC),
  INDEX `fk_TB_MensagemDest_TB_Mensagem1_idx` (`msgd_msgid` ASC),
  CONSTRAINT `fk_TB_MensagemDest_TB_Pessoa1`
    FOREIGN KEY (`msgd_pesid`)
    REFERENCES `dash`.`TB_Pessoa` (`pes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_MensagemDest_TB_Mensagem1`
    FOREIGN KEY (`msgd_msgid`)
    REFERENCES `dash`.`TB_Mensagem` (`msg_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dash`.`TB_Arquivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dash`.`TB_Arquivo` (
  `arq_id` INT NOT NULL AUTO_INCREMENT,
  `arq_msgid` INT NOT NULL,
  `arq_nome` VARCHAR(45) NOT NULL,
  `arq_tamanho` INT NOT NULL,
  PRIMARY KEY (`arq_id`),
  INDEX `fk_TB_Arquivo_TB_Mensagem1_idx` (`arq_msgid` ASC),
  CONSTRAINT `fk_TB_Arquivo_TB_Mensagem1`
    FOREIGN KEY (`arq_msgid`)
    REFERENCES `dash`.`TB_Mensagem` (`msg_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = ujis;


-- -----------------------------------------------------
-- Table `dash`.`TB_AluTur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dash`.`TB_AluTur` (
  `alutur_id` INT NOT NULL,
  `alutur_turid` INT NOT NULL AUTO_INCREMENT,
  `alutur_aluid` INT NOT NULL,
  INDEX `fk_TB_Pessoa_has_TB_Turma_TB_Turma1_idx` (`alutur_aluid` ASC),
  INDEX `fk_TB_Pessoa_has_TB_Turma_TB_Pessoa1_idx` (`alutur_turid` ASC),
  PRIMARY KEY (`alutur_id`),
  CONSTRAINT `fk_TB_Pessoa_has_TB_Turma_TB_Pessoa1`
    FOREIGN KEY (`alutur_turid`)
    REFERENCES `dash`.`TB_Pessoa` (`pes_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_Pessoa_has_TB_Turma_TB_Turma1`
    FOREIGN KEY (`alutur_aluid`)
    REFERENCES `dash`.`TB_Turma` (`tur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
